baseURL = '/'
languageCode = 'en-gb'
title = 'Evolving Complexity'

googleAnalytics = ""
disqusShortname = ""

theme = 'tale'

[permalinks]
    post = "/posts/:title/"
    page = "/:title/"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "About"
        url = "/about/"
    [[menu.main]]
        name = "Tags"
        url = "/tags/"
    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/Ryank90"
        [menu.main.params]
            target = "_blank"
            rel = "noopener"
    [[menu.main]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/ryank90"
        [menu.main.params]
            target = "_blank"
            rel = "noopener"

[params]
    paginate = 8
    css = ["css/custom.css"]
    frontPageSummary = "Hey folks, I am Ryan - I am a software engineering leader, currently serving as VP of Infrastructure at ESL FACEIT Group, where I lead teams across infrastructure, security, and reliability. This blog is my digital brain dump: expect thoughts on technical leadership, infrastructure strategy, AI in engineering orgs, and lessons from the edge of scale."

[params.Author]
    name = "Ryan Kerry"