baseURL = '/'
languageCode = 'en-gb'
title = 'Evolving Complexity'

googleAnalytics = ""
disqusShortname = ""

theme = 'tale'

[permalinks]
    post = "/posts/:title/"
    page = "/:title/"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "About"
        url = "/about/"
    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/Ryank90"
        [menu.main.params]
            target = "_blank"
            rel = "noopener"
    [[menu.main]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/ryank90"
        [menu.main.params]
            target = "_blank"
            rel = "noopener"

[params]
    paginate = 5
    css = ["css/custom.css"]

[params.Author]
    name = "Ryan Kerry"