baseURL = 'https://evolvingcomplexity.com/'
languageCode = 'en-gb'
title = 'Evolving Complexity.'

googleAnalytics = "G-7EWLDVZHCV"
disqusShortname = ""

theme = 'evolving'
enableRobotsTXT = true

[permalinks]
    post = "/posts/:title/"
    page = "/:title/"

[menu]
    # Left navigation menu
    [[menu.left]]
        identifier = "index"
        name = "index"
        title = "Index"
        url = "/"
        weight = 1
    [[menu.left]]
        identifier = "about"
        name = "about"
        title = "About"
        url = "/about/"
        weight = 2
    [[menu.left]]
        identifier = "tags"
        name = "tags"
        title = "Tags"
        url = "/tags/"
        weight = 3
    
    # Right navigation menu (social/contact links)
    [[menu.right]]
        name = "GitHub"
        url = "https://github.com/Ryank90"
        weight = 1
        [menu.right.params]
            target = "_blank"
            rel = "noopener"
    [[menu.right]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/ryank90"
        weight = 2
        [menu.right.params]
            target = "_blank"
            rel = "noopener"

[params]
    paginate = 10

[params.Author]
    name = "Ryan Kerry"

[sitemap]
    changefreq = 'weekly'
    priority = 0.5
    filename = 'sitemap.xml'