on: [push]
name: Deploy Hugo to Firebase
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: ryank90/action-hugo-firebase-deploy@6181d7b6c3158bddd49d3911dcf8c9bb8426109e #v2.0.1
      with:
        firebaseServiceAccount: ${{ secrets.firebase_service_account }}
        projectId: ${{ secrets.firebase_project_name }}
        hugoParams: --gc --minify --buildDrafts=false
