on: [push]
name: Deploy Hugo to Firebase
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: ryank90/action-hugo-firebase-deploy@master
      with:
        firebaseServiceAccount: ${{ secrets.firebase_service_account }}
        projectId: ${{ secrets.firebase_project_name }}
        hugoParams: -D